apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokubeuser-deployment
  labels:
    app: hellokubeuser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellokubeuser
  template:
    metadata:
      labels:
        app: hellokubeuser
    spec:
      containers:
        - name: hellokubeuser-container02
          image: azzahamdy/hellokubeuser:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: hellokubeuser-configmap